language: node_js
node_js:
  - "12"
cache: npm
services:
  - docker
before_script:
  # https://stackoverflow.com/a/27410479
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker run --name incommon -p 5432:5432 -e POSTGRES_PASSWORD=incommon -e POSTGRES_USER=incommon -d postgres
script:
  # - npm run dev:postgres:start
  - npm run test
  # - npm run dev:postgres:stop
  - npm run client:deploy:staging
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master