language: node_js
node_js:
  - "12"
before_install:
  # https://stackoverflow.com/a/27410479
  # Disable services enabled by default
  # http://docs.travis-ci.com/user/database-setup/#MySQL
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - echo $STAGING_PRIVATE_KEY > ~/id_travis
  - echo $STAGING_PUBLIC_KEY > ~/id_travis.pub
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
  - sudo apt update
install:
  - sudo apt install ansible -y
  - echo "remote_tmp     = /tmp/.ansible-\${USER}/tmp" | sudo tee -a /etc/ansible/ansible.cfg
  - npm install
script:
  - npm run ci:test
  - npm run staging:deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master